# Generated by Django 6.0.1 on 2026-01-17 06:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('growth_stage', models.CharField(blank=True, max_length=50)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.field')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.observation')),
            ],
        ),
        migrations.CreateModel(
            name='CropMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_height_cm', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('stalk_diameter_mm', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('green_leaves', models.IntegerField(null=True)),
                ('plant_population', models.IntegerField(null=True)),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crops.observation')),
            ],
        ),
        migrations.CreateModel(
            name='CropManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprayed', models.BooleanField(null=True)),
                ('pesticide_type', models.CharField(blank=True, max_length=100)),
                ('fertilizer_applied', models.BooleanField(null=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=100)),
                ('fertilizer_date', models.DateField(blank=True, null=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crops.observation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FIELD_COLLECTOR', 'Field Collector'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
