# Generated by Django 6.0.1 on 2026-01-17 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.ImageField(upload_to='observations/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
