# Generated by Django 6.0.1 on 2026-01-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_media_image_url_alter_media_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='data_collector_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
