# Generated by Django 6.0.1 on 2026-01-18 08:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_observation_data_collector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
