# Generated by Django 6.0.1 on 2026-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_field_boundary_observation_observation_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropmanagement',
            old_name='pesticide_type',
            new_name='pesticide_used',
        ),
        migrations.RenameField(
            model_name='cropmeasurement',
            old_name='green_leaves',
            new_name='number_of_leaves',
        ),
        migrations.RenameField(
            model_name='cropmeasurement',
            old_name='stalk_diameter_mm',
            new_name='stalk_diameter',
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='watering',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
