# Generated by Django 6.0.1 on 2026-01-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_rename_pesticide_type_cropmanagement_pesticide_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmanagement',
            name='observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_management', to='crops.observation'),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_measurement', to='crops.observation'),
        ),
    ]
