# Generated by Django 6.0.1 on 2026-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_fields',
            field=models.ManyToManyField(blank=True, to='crops.field'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FIELD_MANAGER', 'Field Manager'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
