# Generated by Django 6.0.1 on 2026-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_userprofile_assigned_fields_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the user has access to the system'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(default=list, help_text='Array of permissions like ["write_logs", "upload_gps", "access_camera"]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FIELD_MANAGER', 'Field Manager'), ('FIELD_COLLECTOR', 'Field Collector'), ('VIEWER', 'Viewer')], default='FIELD_COLLECTOR', max_length=20),
        ),
    ]
