# Generated by Django 6.0.1 on 2026-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmanagement',
            name='fertilizer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='irrigation_applied',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='pest_percentage_affected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='pest_present',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='pest_severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='pest_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='urgent_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='watering_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cropmeasurement',
            name='canopy_cover_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cropmeasurement',
            name='soil_moisture_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cropmeasurement',
            name='vigor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cropmeasurement',
            name='weed_pressure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='soil_moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
