# Generated by Django 6.0.1 on 2026-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_cropmanagement_fertilizer_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmanagement',
            name='urgent_attention',
        ),
        migrations.RemoveField(
            model_name='cropmanagement',
            name='watering_details',
        ),
        migrations.AddField(
            model_name='observation',
            name='urgent_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cropmanagement',
            name='pest_severity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='canopy_cover_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='soil_moisture',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='soil_moisture_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='vigor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cropmeasurement',
            name='weed_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
