# Generated by Django 6.0.1 on 2026-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_remove_cropmanagement_urgent_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='client_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
