# Generated by Django 6.0.1 on 2026-01-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0013_observation_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
